### ISSUE TITLE
GitHub Action to autobuild to gh-pages branch

### ISSUE THREAD

**Issue by coliff** [h5bp/Front-end-Developer-Interview-Questions#654]
this looks like it could do the trick:
https://github.com/marketplace/actions/eleventy-action

```yaml
name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
